#!/bin/sh

NGINX_CONFIG_FILE="/etc/nginx/sites-available/localhost"
RELOAD_NGINX="service nginx reload"

if [ "$1" = "on" ] ; then
	grep "autoindex off" >/dev/null 2>&1 $NGINX_CONFIG_FILE \
		&& echo "enabling autoindex" \
		&& sed -i "s/autoindex off/autoindex on/g" $NGINX_CONFIG_FILE \
		&& $RELOAD_NGINX \
		&& echo "autoindex on"
elif [ "$1" = "off" ] ; then
	grep "autoindex on" >/dev/null 2>&1 $NGINX_CONFIG_FILE \
		&& echo "disabling autoindex" \
		&& sed -i "s/autoindex on/autoindex off/g" $NGINX_CONFIG_FILE \
		&& $RELOAD_NGINX \
		&& echo "autoindex off"
else
	DISPLAY_USAGE=1
fi
[ "$?" -ne 0 ] && echo "autoindex already" "$1"
[ "$DISPLAY_USAGE" = 1 ] && echo "Usage: autoindex [on|off]" \
	&& echo "  on,		enable autoindex" \
	&& echo "  off,		disable autoindex"
